### ISSUE TITLE
Short descriptions for each tag

### ISSUE THREAD

**Issue by ozgurakgun** [dlrep/dlrep#32]
@pchristen Now that you have added a number of tags, it becomes obvious that we need some short descriptions for each tag.

If you can write short descriptions after the "header" part of some of the tags files, I can look into rendering them in the website.

For example:

```
---
tag: super duper
---

This tag is for super duper data sets and tasks.

```

**Comment by pchristen** [comment]
OK, will do..

**Comment by ozgurakgun** [comment]
The website part of this was done by #48.

@pchristen feel free to close the issue if you are happy with the descriptions.

Thanks for adding them by the way, very helpful!

**Comment by pchristen** [comment]
How do I close an issue? I cannot see a close button?

**Comment by pchristen** [comment]
Looks like only the person who opened an issue can close it - I cannot close this issue.

**Comment by ozgurakgun** [comment]
OK, I'll close it.
